INPUT_IMAGES_FOLDER = "./data/1_input_images"
IMAGES_WITH_DETECTION_FOLDER = "./data/2_images_with_detection_boxes"
DETECTION_INFO_FOLDER = "./data/3_detection_info"
METADATA_INFO_FOLDER = "./data/4_images_metadata"
PREPARED_IMAGES = "./app/6_prepared_images_for_dashboard"
OBJECT_DETECTED_FOLDER = "./data/5_object_detected"
TRACKING_URI = "."